version: "3.8"

services:
  backend:
    container_name: mail_in_api
    build: backend/
    restart: always
    ports: 
      - 8000:8000

  frontend:
    container_name: mail_in
    build: frontend/
    restart: always
    ports:
      - 3000:3000

